HHblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
]

blog/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from blog import views
from django.conf import settings

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('details/<int:pk>/', views.details, name='details'),
    url(r'mdeditor/', include('mdeditor.urls')),
    path('show_archives/', views.archives, name='archives'),
    path('archives/<int:year>/<int:month>/', views.ArchivesView.as_view(), name='archive'),
    path('show_categories/', views.categories, name='categories'),
    path('categories/<int:pk>/', views.CategoriesView.as_view(), name='category'),
    path('show_tages/', views.tags, name='tags'),
    path('tag/<int:pk>', views.TagsView.as_view(), name='tag'),
    # path('search', views.SearchView.as_view(), name='search'),
    path('search/', views.search, name='search'),
    path('create/', views.article_create, name='create'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('captcha/', views.get_captcha),
    path('increase-likes/<int:id>/', views.IncreaseLikesView.as_view(), name='increase_likes'),
    path('about/', views.about, name='about'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/urls.py
from django.urls import path, include
from comment import views
app_name = 'comment'

urlpatterns = [
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
]

blog/models.py
import markdown
# from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils import timezone
from django.utils.html import strip_tags
from mdeditor.fields import MDTextField


class User(models.Model):

    no = models.AutoField(primary_key=True, verbose_name='编号')
    username = models.CharField(max_length=20, unique=True, verbose_name='用户名')
    password = models.CharField(max_length=32, verbose_name='用户密码')
    email = models.EmailField(max_length=255, default='', blank=True, verbose_name='邮箱')
    tel = models.CharField(max_length=11, verbose_name='手机号')

    class Meta:
        db_table = 'tb_user'
        verbose_name = '用户'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username


class Category(models.Model):
    """分类"""

    name = models.CharField(max_length=128, verbose_name='分类')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'tb_category'
        verbose_name = '博客分类'
        verbose_name_plural = verbose_name


class Tag(models.Model):
    """标签"""

    name = models.CharField(max_length=128, verbose_name='标签')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'tb_tag'
        verbose_name = '标签'
        verbose_name_plural = verbose_name


class Blog(models.Model):

    title = models.CharField(max_length=1024, verbose_name='标题')
    author = models.ForeignKey(to=User, default='xx', verbose_name='作者', on_delete=models.CASCADE)
    img = models.ImageField(upload_to='blog_img', null=True, blank=True, verbose_name='博客图片')
    body = MDTextField(verbose_name='正文')
    abstract = models.TextField(max_length=256, null=True, blank=True, verbose_name='摘要')
    visiting = models.PositiveIntegerField(default=0, verbose_name='访问量')
    category = models.ManyToManyField(Category, verbose_name='博客分类')
    tags = models.ManyToManyField(Tag, verbose_name='标签')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    modifyed_time = models.DateTimeField(auto_now=True, verbose_name='修改时间')
    likes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'tb_blog'
        ordering = ['-created_time']
        verbose_name = '博客'
        verbose_name_plural = verbose_name

    def get_absolute_url(self):
        return reverse('blog:details', args={self.id})

    def increase_visiting(self):
        self.visiting += 1
        self.save(update_fields=['visiting'])

    def save(self, *args, **kwargs):
        self.modified_time = timezone.now()

        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])

        self.abstract = strip_tags(md.convert(self.body))[:256]
        super().save(*args, **kwargs)

blog/forms.py
from django import forms
from mdeditor.fields import MDTextFormField
from blog.models import Blog, User

import hashlib
import re

from django.core.exceptions import ValidationError


# from mdeditor.fields import MDTextFormField


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = Blog
        # fields = '__all__'
        fields = ('title', 'body')


class MDEditorForm(forms.Form):
    name = forms.CharField()
    content = MDTextFormField()


USERNAME_PATTERN = re.compile(r'\w{6,20}')
TEL_PATTERN = re.compile(r'1[3-9]\d{9}')


def password_to_md5(password):
    """获取密码的MD5摘要"""
    return hashlib.md5(password.encode()).hexdigest()


def check_username(username):
    """验证用户名是否有效"""
    matcher = USERNAME_PATTERN.fullmatch(username)
    if not matcher:
        raise ValidationError('用户名由字母、数字、下划线构成且长度为6-20')
    return username


def check_password(password):
    if len(password) < 8:
        raise ValidationError('密码长度不应该小于8个字符')
    return password_to_md5(password)


class LoginForm(forms.Form):
    username = forms.CharField(min_length=6, max_length=20)
    password = forms.CharField(min_length=8, max_length=20)
    code = forms.CharField(min_length=4, max_length=4)

    def clean_username(self):
        return check_username(self.cleaned_data['username'])

    def clean_password(self):
        return check_password(self.cleaned_data['password'])


class UserForm(forms.ModelForm):
    password = forms.CharField(min_length=8, max_length=20,
                               widget=forms.PasswordInput, label='密码')

    def clean_username(self):
        return check_username(self.cleaned_data['username'])

    def clean_password(self):
        return check_password(self.cleaned_data['password'])

    def clean_tel(self):
        tel = self.cleaned_data['tel']
        matcher = TEL_PATTERN.fullmatch(tel)
        if not matcher:
            raise ValidationError('无效的手机号码')
        return tel

    class Meta:
        model = User
        exclude = ('no',)


class RegisterForm(UserForm):
    repassword = forms.CharField(min_length=8, max_length=20)
    code = forms.CharField(min_length=6, max_length=6)
    agreement = forms.BooleanField(required=True)

    def clean_repassword(self):
        password = self.cleaned_data['password']
        repassword = self.cleaned_data['repassword']
        if password != password_to_md5(repassword):
            raise ValidationError('密码和确认密码需要一致')
        return repassword

blog/views.py
import re
import json
import markdown
import requests
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.text import slugify
from django.views.generic import ListView
from django.views.generic.base import View
from markdown.extensions.toc import TocExtension
from blog.forms import RegisterForm, LoginForm, TEL_PATTERN
from blog.utils import generate_captcha_code, generate_mobile_code
from blog.captcha import Captcha
# 分页插件pure_pagination
# from pure_pagination import PaginationMixin

# Create your views here.
from blog.models import Blog, Tag, Category, User
from comment.models import Comment
from blog.forms import BlogPostForm, MDEditorForm

from django.db.models.aggregates import Count

md = markdown.Markdown(extensions=[
    'markdown.extensions.extra',
    'markdown.extensions.codehilite',
    # 'markdown.extensions.toc',
    TocExtension(slugify=slugify),
])


# 分页插件pure_pagination
# class IndexView(PaginationMixin, ListView):


class IndexBaseView(ListView):  # 列表展示类，包含分页功能
    template_name = 'blog/index.html'
    context_object_name = 'texts'
    paginate_by = 4
    model = Blog


class IndexView(IndexBaseView):
    def get_queryset(self):
        texts = Blog.objects.all()
        for text in texts:
            text.abstract = md.convert(text.abstract)
        return texts


def detail(request, pk):
    article = get_object_or_404(Blog, pk=pk)

    article.body = md.convert(article.body)
    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    article.toc = m.group(1) if m is not None else ''
    # article.toc = md.toc
    article.increase_visiting()

    return render(request, 'blog/detail.html', context={'article': article})


def details(request, pk):
    article = get_object_or_404(Blog, pk=pk)
    comments = Comment.objects.filter(article=pk).order_by('-created')
    article.increase_visiting()
    return render(request, 'blog/test.html', context={'article': article, 'comments': comments})


def archives(request):
    context = {'date_list': Blog.objects.dates('created_time', 'month', order='DESC')}

    return render(request, 'blog/archive.html', context)


class ArchivesView(IndexBaseView):
    def get_queryset(self):
        year = self.kwargs['year']
        month = self.kwargs['month']
        texts = Blog.objects.filter(created_time__year=year,
                                    created_time__month=month
                                    ).order_by('-created_time')
        return texts


def categories(request):
    context = {'category_list': Category.objects.annotate(num_blogs=Count('blog')).filter(num_blogs__gt=0), }
    return render(request, 'blog/categories.html', context=context)


class CategoriesView(IndexBaseView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs['pk'])
        texts = Blog.objects.filter(category=cate).order_by('-created_time')
        return texts


def tags(request):
    context = {'tag_list': Tag.objects.annotate(num_blogs=Count('blog')).filter(num_blogs__gt=0)}
    return render(request, 'blog/tags.html', context=context)


class TagsView(IndexBaseView):
    def get_queryset(self):
        if self.kwargs:
            tag = get_object_or_404(Tag, pk=self.kwargs['pk'])
            texts = Blog.objects.filter(tags=tag).order_by('-created_time')
            return texts
        else:
            self.template_name = 'blog/tags.html'
            self.context_object_name = 'context'
            context = {'tag_list': Tag.objects.annotate(num_blogs=Count('blog')).filter(num_blogs__gt=0)}
            return context


def search(request):
    q = request.GET.get('q')

    if not q:
        error_msg = "请输入搜索关键词"
        messages.add_message(request, messages.ERROR, error_msg, extra_tags='danger')
        return redirect('blog:index')

    post_list = Blog.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', {'texts': post_list, 'q': q})


class SearchView(IndexBaseView):
    # def get_context_data(self, **kwargs):
    #     q = self.request.GET.get('q')
    #     context = super(SearchView, self).get_context_data(**kwargs)
    #     context['q'] = q
    #     return context

    def get_queryset(self):
        q = self.request.GET.get('q')
        if not q:
            error_msg = "请输入搜索关键词"
            messages.add_message(self.request, messages.ERROR, error_msg, extra_tags='danger')
            return redirect('blog:index')

        texts = Blog.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))

        return texts


def article_create(request):
    if request.session['userid'] == 2:
        if request.method == "POST":
            article_post_form = BlogPostForm(data=request.POST)
            content_form = MDEditorForm(request.POST)
            if article_post_form.is_valid():
                new_article = article_post_form.save(commit=False)
                new_article.author = User.objects.get(no=request.session['userid'])
                # if request.POST['category'] != 'none':
                    # new_article.colum = Category.objects.get(id=request.POST['category'])

                # if request.POST['tag'] != 'none':
                #     new_article.tags = Category.objects.get(id=request.POST['tag'])
                # new_article.category.add(Category.objects.get[])
                # new_article.tags = '网络'
                new_article.save()
                article_post_form.save_m2m()
                if request.POST['category'] != 'none':
                    new_article.category.add(get_object_or_404(Category, id=request.POST['category']))
                # if request.POST['tag'] != 'none':
                #     try:
                #         new_article.tags.add(get_object_or_404(Tag, id=request.POST['tag']))
                #     except:
                #         pass
                return redirect('blog:index')
            else:
                return HttpResponse("表单内容有误，请重新填写。")
        else:
            article_post_form = BlogPostForm()
            categories = Category.objects.all()
            tags = Tag.objects.all()
            context = {'article_post_form': article_post_form, 'categories': categories, 'tags': tags}
            return render(request, 'blog/create.html', context)
    else:
        return render(request, 'blog/create.html', {'error': '您无权发表文章'})


def get_mobile_code(request):
    """获得手机验证码"""
    tel = request.GET.get('tel')
    if TEL_PATTERN.fullmatch(tel):
        code = generate_mobile_code()
        request.session['mobile_code'] = code
        resp = requests.post(
            url='http://sms-api.luosimao.com/v1/send.json',
            auth=('api', 'key-6d2417156fefbd9c0e78fae069a34580'),
            data={
                'mobile': tel,
                'message': f'您的短信验证码是{code}，打死也不能告诉别人。【Python小课】',
            },
            timeout=3,
            verify=False
        )
        if json.loads(resp.text)['error'] == 0:
            code, hint = 20001, '短信验证码发送成功'
        else:
            code, hint = 20002, '短信验证码发送失败，请稍后重试'
    else:
        code, hint = 20003, '请输入有效的手机号码'
    return JsonResponse({'code': code, 'hint': hint})


def register(request):
    """用户注册"""
    hint = ''
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            code_from_session = '123456'  # request.session.get('mobile_code')
            code_from_user = form.cleaned_data['code']
            if code_from_session == code_from_user:
                form.save()
                hint = '注册成功，请登录!'
                # return render(request, 'blog/login.html', {'hint': hint})
                return redirect('blog:login')
            else:
                hint = '请输入正确的手机验证码'
        else:
            hint = '请输入有效的注册信息'
    return render(request, 'blog/register.html', {'hint': hint})


def login(request):
    """用户登录"""
    hint = ''
    backurl = request.GET.get('backurl', 'blog:index')
    if request.method == 'POST':
        backurl = request.POST['backurl']
        form = LoginForm(request.POST)
        if form.is_valid():
            code_from_session = request.session.get('captcha_code')
            code_from_user = form.cleaned_data['code']
            if code_from_session.lower() == code_from_user.lower():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                user = User.objects.filter(
                    username=username, password=password).first()
                if user:
                    request.session['userid'] = user.no
                    request.session['username'] = user.username
                    return redirect(backurl)
                else:
                    hint = '用户名或密码错误'
            else:
                hint = '请输入正确的验证码'
        else:
            hint = '请输入有效的登录信息'
    return render(request, 'blog/login.html', {'hint': hint, 'backurl': backurl})


def get_captcha(request):
    """生成图片验证码"""
    code = generate_captcha_code()
    request.session['captcha_code'] = code
    image_data = Captcha.instance().generate(code, fmt='PNG')
    return HttpResponse(image_data, content_type='image/png')


def logout(request):
    """用户注销"""
    request.session.flush()
    return redirect('blog:index')


class IncreaseLikesView(View):
    def post(self, request, *args, **kwargs):
        article = Blog.objects.get(id=kwargs.get('id'))
        article.likes += 1
        article.save()
        return HttpResponse('success')


def about(request):
    context = {'name': 'yjh'}
    return render(request, 'blog/about.html', context)

# TODO
#  test
#  cache

blog/templates/blog/about.html
{% extends 'blog/base.html' %}


{% block content %}

    <h1>我是谁谁谁</h1>
    <h1>{{ name }}</h1>
{% endblock %}

blog/templates/blog/archive.html
{% extends 'blog/base.html' %}

{% block content %}

    <div class="widget widget-archives">
        <h3 class="widget-title">归档</h3>
        <ul>
            {% for date in date_list %}
                <li>
                    <a href="{% url 'blog:archive' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                </li>
            {% empty %}
                暂无归档！
            {% endfor %}
        </ul>
    </div>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
{#{% load blog_extras %}#}
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog - 杨京辉</title>
    <meta name="description" content="Your blog page description"/>
    <link href="https://fonts.googleapis.com/css?family=Arimo:400,600,700" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'blog/images/favicon.png' %}">
    <link href="{% static 'blog/styles/main.css' %}" rel="stylesheet">

    <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">
    <style>
        .codehilite {
            padding: 0;
        }

        /* for block of numbers */
        .hljs-ln-numbers {
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;

            text-align: center;
            color: #ccc;
            border-right: 1px solid #CCC;
            vertical-align: top;
            padding-right: 5px;
        }

        .hljs-ln-n {
            width: 30px;
        }

        /* for block of code */
        .hljs-ln .hljs-ln-code {
            padding-left: 10px;
            white-space: pre;
        }

        .pp-section p img {
            width: 100%;
            margin-top: 10px;
        }

    </style>
</head>
<body id="top">
<div class="page">
    <header>
        <div class="pp-header">
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container"><a href="{% url 'blog:index' %}"><img
                        src="{% static 'blog/images/favicon.png' %}"></a><a class="navbar-brand"
                                                                            href="{% url 'blog:index' %}"></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                            aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <ul class="navbar-nav ml-auto">

                            <li class="nav-item">
                                <div class="row">
                                    <div class="col-auto mr-auto" style="padding-top: 4px">
                                        <form class="form-inline" action="{% url 'blog:search' %}">
                                            <label class="sr-only">content</label>
                                            <input type="text"
                                                   class="form-control mb-2 mr-sm-2"
                                                   name="q"
                                                   placeholder="搜索文章..."
                                                   required
                                            >
                                        </form>
                                    </div>
                                </div>
                            </li>
                            <li class="nav-item {% if request.resolver_match.url_name == 'index' %} active {% endif %} ">
                                <a class="nav-link" href="{% url 'blog:index' %}">主页</a>
                            </li>
                            <li class="nav-item {% if request.resolver_match.url_name == 'archives' %} active {% endif %}">
                                <a class="nav-link" href="{% url 'blog:archives' %}">归档</a>
                            </li>
                            <li class="nav-item {% if request.resolver_match.url_name == 'categories' %} active {% endif %}">
                                <a class="nav-link" href="{% url 'blog:categories' %}">分类</a>
                            </li>
                            <li class="nav-item {% if request.resolver_match.url_name == 'tags' %} active {% endif %}">
                                <a class="nav-link" href="{% url 'blog:tags' %}">标签</a>
                            </li>
                            <li class="nav-item {% if request.resolver_match.url_name == '' %} active {% endif %}"><a
                                    class="nav-link" href="{% url 'blog:about' %}">关于</a></li>
                            <li class="nav-item {% if request.resolver_match.url_name == 'create' %} active {% endif %} ">
                                <a class="nav-link" href="{% url 'blog:create' %}">发布</a></li>
                            <li class="nav-item {% if request.resolver_match.url_name == 'login' %} active {% endif %} ">
                                {% if request.session.username %}
                                    <a class="nav-link" href="#">{{ request.session.username }}</a>
                                {% else %}
                                    <a class="nav-link" href="{% url 'blog:login' %}">
                                    登录
                                {% endif %}
                                </a>
                            </li>
                            <li class="nav-item {% if request.resolver_match.url_name == 'louout' %} active {% endif %} ">
                                {% if request.session.username %}
                                    <a class="nav-link" href="{% url 'blog:logout' %}">注销</a></li>
                                {% else %}
                                    <a class="nav-link" href="{% url 'blog:register' %}">注册</a></li>
                                {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <link href="blog/images/favicon.png" rel="icon" type="image/x-ico">
    </header>
    <div class="page-content">

        <div class="container">

            <div class="pp-section pp-container-readable">
                {% block content %}
                    <article class="pp-post"><a href="blog-post.html"><img class="img-fluid" src="images/blog-1.jpg"
                                                                           alt="Blog Image"/></a>
                        <header class="pp-post-header">
                            <div class="pp-post-title"><a class="h4" href="blog-post.html">Healthy Meals for Busy
                                Morning</a></div>
                            <div class="pp-post-meta">
                                <ul>
                                    <li><i class="fa fa-calendar-check-o"
                                           aria-hidden="true"></i><span>November 04, 2017</span></li>
                                    <li><i class="fa fa-tags" aria-hidden="true"></i><span><a
                                            href="#"><span>Branding</span></a>, <a
                                            href="#"><span>Design</span></a></span></li>
                                    <li><i class="fa fa-comments" aria-hidden="true"></i><a href="#">Comments</a></li>
                                </ul>
                            </div>
                        </header>
                        <div class="pp-post-content">
                            <p>Whether you've just got a new camera and are looking to learn some new photography
                                techniques or have been shooting for a while and want to master some old ones, this
                                essential photographer's resource is here to help.</p>
                        </div>
                        <div class="pp-post-read-more"><a href="blog-post.html">Read More</a></div>
                    </article>
                {% endblock %}
                {#                {% block page %}#}
                {#                {% endblock %}#}


                <div class="pp-pagination" style="text-align: center">
                    <ul>
                        {#            上一页按钮#}
                        {% if page_obj.has_previous %}
                            <li><a href="?page={{ page_obj.previous_page_number }}">← 上一页</a></li>
                        {% endif %}
                        {#            超过4页的分页形式#}
                        {% if page_obj.paginator.num_pages > 4 %}
                            {% if page_obj.number == 1 %}         {#第一页处理#}
                            {% else %}
                                {% if page_obj.number|add:-1 == 1 %}{#                    第二页处理#}
                                    <li><a href="?page=1">1</a></li>
                                {% else %}
                                    <li><a href="?page=1">首页</a></li>
                                {% endif %}
                            {% endif %}

                            {% if page_obj.number > 2 %}
                                <li>...</li>
                                {#                    当前页的前一页#}
                                <li><a href="?page={{ page_obj.number | add:-1 }}">{{ page_obj.number | add:-1 }}</a>
                                </li>
                            {% endif %}
                            {#                当前页#}
                            <li><a style="color: black" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
                            </li>

                            {% if page_obj.number == page_obj.paginator.num_pages %}
                            {% else %}
                                {#                    当前页的下一页#}
                                <li><a href="?page={{ page_obj.number|add:1 }}">{{ page_obj.number|add:1 }}</a></li>
                                {#                    倒数第二页处理#}
                                {% if page_obj.number|add:1 == page_obj.paginator.num_pages %}
                                {% else %}
                                    <lī>...</lī>
                                    <li><a href="?page={{ page_obj.paginator.num_pages }}">尾页</a></li>
                                {% endif %}
                            {% endif %}

                        {% endif %}

                        {#            小于4页的分页形式#}
                        {% if page_obj.paginator.num_pages <= 4 %}
                            {% for num in page_obj.paginator.page_range %}
                                <li><a {% if num == page_obj.number %} style="color: black" {% endif %}
                                                                       href="?page={{ num }}">{{ num }}</a></li>
                            {% endfor %}
                        {% endif %}
                        {% if page_obj.has_next %}
                            <li><a href="?page={{ page_obj.next_page_number }}">下一页 →</a></li>
                        {% endif %}
                    </ul>
                </div>

                {#    分页插件pure_pagination#}
                {#    <div class="pp-pagination" style="text-align: center">#}
                {#        <ul>#}
                {#            {% if is_paginated %}#}
                {#                <li>{{ page_obj.render }}</li>#}
                {#            {% endif %}#}
                {#        </ul>#}
                {#    </div>#}


            </div>

            <div class="pp-section"></div>

        </div>
    </div>
    <footer class="pp-footer">
        <div class="container py-5">
            <div class="row text-center">
                <div class="col-md-12"><a class="pp-facebook btn btn-link" href="#"><i class="fa fa-facebook fa-2x "
                                                                                       aria-hidden="true"></i></a><a
                        class="pp-twitter btn btn-link " href="#"><i class="fa fa-twitter fa-2x "
                                                                     aria-hidden="true"></i></a><a
                        class="pp-google-plus btn btn-link" href="#"><i class="fa fa-google-plus fa-2x"
                                                                        aria-hidden="true"></i></a><a
                        class="pp-instagram btn btn-link" href="#"><i class="fa fa-instagram fa-2x "
                                                                      aria-hidden="true"></i></a></div>
                <div class="col-md-12">
                    <p class="mt-3">Copyright &copy; Blog. All rights reserved.<br>
                        {#                        <a#}
                        {#                            href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a#}
                        {#                            href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a></p>#}
                </div>
            </div>
        </div>
    </footer>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="{% static 'blog/scripts/main.js' %}"></script>
<script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
<script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
</script>
<script src="{% static 'blog/scripts/csrf.js' %}"></script>

{#{% show_recent_posts %}#}
{#{% show_archives %}#}
{#{% show_categories %}#}
{#{% show_tags %}#}
</body>
</html>